import { create } from "zustand";
let _nid = 0;
export const useZendaya = create((set) => ({
    ai: "idle",
    text: "",
    audioLevel: 0,
    connected: false,
    scene: "main",
    panel: "none",
    activeModule: "none",
    dockCorner: "br",
    docked: false,
    voiceActive: false,
    terminalOpen: false,
    minimized: false,
    speakerAzimuth: 0,
    notifications: [],
    bgDim: 0,
    fogDensity: 0.04,
    quality: "high",
    fps: 60,
    setAi: (s) => set({ ai: s }),
    setText: (t) => set({ text: t }),
    setAudioLevel: (l) => set({ audioLevel: l }),
    setConnected: (b) => set({ connected: b }),
    setScene: (s) => set({ scene: s }),
    setPanel: (p) => set({ panel: p }),
    setActiveModule: (m) => set({ activeModule: m, docked: m !== "none" }),
    setDockCorner: (c) => set({ dockCorner: c }),
    setDocked: (b) => set({ docked: b }),
    setVoiceActive: (b) => set({ voiceActive: b }),
    setTerminalOpen: (b) => set({ terminalOpen: b }),
    setMinimized: (b) => set({ minimized: b }),
    setSpeakerAzimuth: (a) => set({ speakerAzimuth: a }),
    pushNotification: (text) => set((s) => ({
        notifications: [
            ...s.notifications,
            { id: ++_nid, text, ts: Date.now() },
        ].slice(-5),
    })),
    popNotification: (id) => set((s) => ({ notifications: s.notifications.filter((n) => n.id !== id) })),
    setBgDim: (v) => set({ bgDim: Math.max(0, Math.min(1, v)) }),
    setFogDensity: (v) => set({ fogDensity: Math.max(0, v) }),
    setQuality: (q) => set({ quality: q }),
    setFps: (n) => set({ fps: n }),
}));
